title: pjsk.
email: peterjskennedy@example.com
description: Where I over (and under) engineer all sorts of things
baseurl: "/"
url: "http://pjsk.io"
twitter_username: peterjskennedy
github_username:  pjskennedy
# Build settings
markdown: kramdown
